### PR TITLE
Aligned and Updated the metrics values

### PR DESCRIPTION
**Pull request by AakashJethva09**

### CODE REVIEW

**Comment by AakashJethva09** [comment]
So I have aligned all the metrics alphabetically and changed 3 of the metrics values as provided by Dirk Butson. Rest of the file remains the same without any indentation changes. 
FYI: Metrics values change for these three
DiskWritten:                          MONITOR_DELTA,
JrnlBytes:                              MONITOR_DELTA,
JrnlWrites:                             MONITOR_DELTA,

**Comment by thebithead** [comment]
> So I have aligned all the metrics alphabetically and changed 3 of the metrics values as provided by Dirk Butson. Rest of the file remains the same without any indentation changes.
> FYI: Metrics values change for these three
> DiskWritten: MONITOR_DELTA,
> JrnlBytes: MONITOR_DELTA,
> JrnlWrites: MONITOR_DELTA,

I thought we agreed we would remove the alphabetical sorting, because it makes it hard to see what lines you changed.  How about we do the alphabetical sorting in a separate pull request.

**Comment by AakashJethva09** [comment]
> > So I have aligned all the metrics alphabetically and changed 3 of the metrics values as provided by Dirk Butson. Rest of the file remains the same without any indentation changes.
> > FYI: Metrics values change for these three
> > DiskWritten: MONITOR_DELTA,
> > JrnlBytes: MONITOR_DELTA,
> > JrnlWrites: MONITOR_DELTA,
> 
> I thought we agreed we would remove the alphabetical sorting, because it makes it hard to see what lines you changed. How about we do the alphabetical sorting in a separate pull request.

Sorry for that. Do you want me raise another pull request? It would mean, I will have to revert the change and do it again.I have mentioned the values which have changed.  Also, I arranged it alphabetically so that it would be easier in future for any further changes in the values.

**Comment by thebithead** [comment]
You don't need a new Pull Request.  You can just revert your change, change the three lines, and then push your change.  GitHub will automatically detect your changes and update the diffs.

**Comment by AakashJethva09** [comment]
> You don't need a new Pull Request. You can just revert your change, change the three lines, and then push your change. GitHub will automatically detect your changes and update the diffs.

Hey tom, So I have updated the file and removed the alphabetical sorting.

**Comment by thebithead** [comment]
Looks good.  I will merge this when it passes the tests on TravisCI.

**Pull request merged**
